### ISSUE TITLE
API Updated

### ISSUE THREAD

**Issue by darrensteele** [cassou/VL53L0X_rasp#2]
Hi,

The API has been updated recently to 1.0.2 - I modified your build to expect 1.0.2 but now I am getting failures.  Could you please check if your implementation still works with 1.0.2.  I'm trying to debug but I'm unsure if it's my soldering, my old raspberry pi, my misunderstanding of how this sensor works or if the API update broke something in your code.  Helpfully the documentation is not particularly descriptive about what changed :(

**Comment by cassou** [comment]
Hi,

I will try to have a look, but this project is in a drawer somewhere, I'll have to dig it out ;)

**Comment by cassou** [comment]
Hi Darrentsteele,
On my side nothing broke with 1.0.2.
I pushed a cosmetic fix but that change nothing to the actual code.

The only thing you have to change is the path to the api (on my setup it is API_DIR=../VL53L0X_1.0.2)

**Comment by darrensteele** [comment]
Cool. Thanks for checking. It must be a hardware thing for me then. I'll carry on looking into it.
