### ISSUE TITLE
Varied Results

### ISSUE THREAD

**Issue by owl770** [cassou/VL53L0X_rasp#3]
Hi,

Thanks for taking the time to write this library.

I am using a VL53L0X on a RPi3 to measure the water level in a tank. The tank is a large (105,000 litre) concrete tank, sunk into the ground. No light gets in, it's dark inside. The RPi is mounted on the top of the tank in a weatherproof box and the VL53L0X "sees" down through a hole in the box. As you can imagine, the water level is fairly static and the surface calm.

I used your code from the vl53l0x_SingleRanging_Long_Range_Example.c example but seem to get wildly varying results...
Measured distance: 254
Measured distance: 261
Measured distance: 251
Measured distance: 268
Measured distance: 246
Measured distance: 262
Measured distance: 262
Measured distance: 265
Measured distance: 252
Measured distance: 256
Measured distance: 252
Measured distance: 252
Measured distance: 261
Measured distance: 268
Measured distance: 267
Measured distance: 254
Measured distance: 261
Measured distance: 264
Measured distance: 270
Measured distance: 257
Measured distance: 259
Measured distance: 254
Measured distance: 257
Measured distance: 252
Measured distance: 257
Measured distance: 255
Measured distance: 251
Measured distance: 249
Measured distance: 252
Measured distance: 255
Measured distance: 253
Measured distance: 261
Measured distance: 262
Measured distance: 253
Measured distance: 252
Measured distance: 263
Measured distance: 277
Measured distance: 252
Measured distance: 261
Measured distance: 264
Measured distance: 268
Measured distance: 270
Measured distance: 262
Measured distance: 244
Measured distance: 272
Measured distance: 253
Measured distance: 283
Measured distance: 250
Measured distance: 253
Measured distance: 258

Min=244 and Max=283. I was assuming this sensor would be quite accurate with minimal variation.

I need to be able to measure from about 110mm to around 1780mm.

Do you have any suggestions on how to improve the accuracy or minimise the variation? The manual talks about a "High Accuracy" setting but a max range of 1.2m - that might have to do, if it works.

Thanks.

**Comment by owl770** [comment]
Hi - I have enhanced my program to allow you to select either "Long Range" or "High Accuracy" mode. It takes 10 samples and then the average of those samples. It also tracks the min and max values in each group of 10 samples.
In "High Accuracy" mode, the measurements seem more consistent with a variation of around 5 to 15mm. That's better than "Long Range" mode but still seems a fairly wide range to me.
Not sure how to improve the consistency of the measurements. Do you think the fact that it is trying to measure the distance to water has something to do with it?

**Comment by cassou** [comment]
Hi !
I am sorry but I can't help you a lot here. I did not played a lot with the different modes of the sensor.
I would suggest you to try on something solid to see if you keep seeing those variations.

And since I moved recently the sensor is in a box, somewhere in a bigger box, stored in a stack of boxes...I am not able to test.

**Comment by owl770** [comment]
Hi - did a bit more reading online and discovered that most VL53L0X's are delivered with a protective film over the sensor!!! I checked and then removed the protective film. OOPS. Readings are very different now but still vary 5-10mm. Getting better.
