### ISSUE TITLE
Changed Firmware / examples correct?

### ISSUE THREAD

**Issue by ludwich66** [cassou/VL53L0X_rasp#4]
I receive this error after compiling the examples:
`pi@raspberrypi:~/VL53L0X_rasp-master/bin $ ./vl53l0x_ContinuousRanging_Example`
`VL53L0X PAL Continuous Ranging example`
`VL53L0X API Version Error: Your firmware has 1.0.2 (revision 4823). This example requires 1.0.1.`
`Call of VL53L0X_DataInit`
`Failed to write to the i2c bus.`
`Failed to write to the i2c bus.`
`Failed to write to the i2c bus.`
`Failed to write to the i2c bus.`
`Failed to write to the i2c bus.`
`Failed to write to the i2c bus.`
`Failed to write to the i2c bus.`
`Failed to write to the i2c bus.`
`API Status: -20 : Control Interface Error`
`API Status: -20 : Control Interface Error`
`Close Comms`
`VL53L0X_i2c_close`
`API Status: -20 : Control Interface Error`

My Action --> change the examples from 1 to 2
`#define VERSION_REQUIRED_MAJOR 1`
`#define VERSION_REQUIRED_MINOR 0`
`#define VERSION_REQUIRED_BUILD **2**`
i don't know if it is the wright way, but the API Version error disappeared

my next Problem: `Failed to write to the i2c bus.`
This is the answer from i2cdetect on bus 1 (Raspi2)

`pi@raspberrypi:~/VL53L0X_rasp-master/bin $ i2cdetect -y 1`
`     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f`
`00:          -- -- -- -- -- -- -- -- -- -- -- -- -- `
`10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- `
`20: -- -- -- -- -- -- -- -- -- 29 -- -- -- -- -- -- `
`30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- `
`40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- `
`50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- `
`60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- `
`70: -- -- -- -- -- -- -- --                     ` 

Hardware:
CJMCU-530
Raspi2B

Any tipps for me?

**Comment by cassou** [comment]
Hi ludwich66,

Could you provide a pull request with the check for VERSION_REQUIRED_BUILD removed ?
I do not think this is really required (this is here because it was in the original ST examples).

For the i2c issue, I do not have the harware with me (I can't test), did you try the other i2c bus ?

**Comment by rmarszew** [comment]
I've just downloaded the latest version and having the exactly same output:
Example 
VL53L0X PAL Continuous Ranging example

VL53L0X API Version Error: Your firmware has 1.0.2 (revision 4823). This example requires 1.0.1.
Call of VL53L0X_DataInit
Failed to write to the i2c bus.
Failed to write to the i2c bus.
Failed to write to the i2c bus.
Failed to write to the i2c bus.
Failed to write to the i2c bus.
Failed to write to the i2c bus.
Failed to write to the i2c bus.
Failed to write to the i2c bus.
API Status: -20 : Control Interface Error
API Status: -20 : Control Interface Error
Close Comms
VL53L0X_i2c_close
API Status: -20 : Control Interface Error
pi@raspberrypi:~/scripts/VL/VL53L0X_rasp/bin $
